#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def find(k,p):
    for i in range(len(p)):
        if p[i]==k:
            return i+1
    return 0
def permutationEquation(p):
    y=[0 for _ in range(len(p))]
    for i in range(len(p)):
        y[i] = find(find(i+1,p),p)
    return y

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
